version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"   # Location of pom.xml (repo root)
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Zurich"

    open-pull-requests-limit: 5

    commit-message:
      prefix: "deps"

    labels:
      - dependencies

    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"